import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { Inter,Anek_Telugu } from "next/font/google";
import "./globals.css";
import { GeistSans } from "geist/font/sans";

const anekTelugu = Anek_Telugu ({ subsets: ["latin"],
  variable: "--font-caption"
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={cn(GeistSans.variable, anekTelugu, "font-sans h-full bg-background text-bacground")}>{children}</body>
    </html>
  );
}
